name: yarn_deploy_to_npm
on:
  push:
    # DO NOT add branch 'main' there as the conditions works as an AND operation
    # We only want to run the action on tag push, not every main push
    tags:        
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v2
    # Setup Node.js environment
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
        registry-url: 'https://registry.npmjs.org'
    # Install dependencies and build your package (if needed).
    - name: Install dependencies and build 🔧
      run: yarn
    - name: Publish package on NPM 📦
      run: yarn publish --allow-warnings --verbose
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}   # You need to set this in your repo settings
        